const data = [
  {
    productInformation: '2 Classic Collection Garage Door, 2 Entry Door',
    cartName: 'Johnson_Classic14209123',
    shippingPoint: "Russia Plant",
    createdBy: 'Manoj Bajpayee',
    expiry: 4,
  },
  {
    productInformation: "10' 0'' X 10' 0.0'' CAN211CCW1 COMPLETE DOOR INTELLICORE",
    cartName: "Carter_Classic14209123",
    shippingPoint: "Russia Plant",
    createdBy: 'Jamie Sunshine',
    expiry: 90,
  },
  {
    productInformation: "Canyon Ridge® Collection Ultra-Grain® Series with Intellicore®",
    cartName: "Michigan_Classic14209123",
    shippingPoint: "ABC Plant",
    createdBy: 'Steve Benneth...',
    expiry: 4,
  },
  {
    productInformation: '2 Classic Collection Garage Door, 2 Entry Door',
    cartName: 'Johnson_Classic14209123',
    shippingPoint: "Russia Plant",
    createdBy: 'Manoj Bajpayee',
    expiry: 4,
  },
  {
    productInformation: "10' 0'' X 10' 0.0'' CAN211CCW1 COMPLETE DOOR INTELLICORE",
    cartName: "Carter_Classic14209123",
    shippingPoint: "Russia Plant",
    createdBy: 'Jamie Sunshine',
    expiry: 90,
  },
  {
    productInformation: "Canyon Ridge® Collection Ultra-Grain® Series with Intellicore®",
    cartName: "Michigan_Classic14209123",
    shippingPoint: "ABC Plant",
    createdBy: 'Steve Benneth...',
    expiry: 4,
  },
  {
    productInformation: '2 Classic Collection Garage Door, 2 Entry Door',
    cartName: 'Johnson_Classic14209123',
    shippingPoint: "Russia Plant",
    createdBy: 'Manoj Bajpayee',
    expiry: 4,
  },
  {
    productInformation: "10' 0'' X 10' 0.0'' CAN211CCW1 COMPLETE DOOR INTELLICORE",
    cartName: "Carter_Classic14209123",
    shippingPoint: "Russia Plant",
    createdBy: 'Jamie Sunshine',
    expiry: 90,
  },
  {
    productInformation: "Canyon Ridge® Collection Ultra-Grain® Series with Intellicore®",
    cartName: "Michigan_Classic14209123",
    shippingPoint: "ABC Plant",
    createdBy: 'Steve Benneth...',
    expiry: 4,
  },
  {
    productInformation: '2 Classic Collection Garage Door, 2 Entry Door',
    cartName: 'Johnson_Classic14209123',
    shippingPoint: "Russia Plant",
    createdBy: 'Manoj Bajpayee',
    expiry: 4,
  },
  {
    productInformation: "10' 0'' X 10' 0.0'' CAN211CCW1 COMPLETE DOOR INTELLICORE",
    cartName: "Carter_Classic14209123",
    shippingPoint: "Russia Plant",
    createdBy: 'Jamie Sunshine',
    expiry: 90,
  },
  {
    productInformation: "Canyon Ridge® Collection Ultra-Grain® Series with Intellicore®",
    cartName: "Michigan_Classic14209123",
    shippingPoint: "ABC Plant",
    createdBy: 'Steve Benneth...',
    expiry: 4,
  },
  {
    productInformation: '2 Classic Collection Garage Door, 2 Entry Door',
    cartName: 'Johnson_Classic14209123',
    shippingPoint: "Russia Plant",
    createdBy: 'Manoj Bajpayee',
    expiry: 4,
  },
  {
    productInformation: "10' 0'' X 10' 0.0'' CAN211CCW1 COMPLETE DOOR INTELLICORE",
    cartName: "Carter_Classic14209123",
    shippingPoint: "Russia Plant",
    createdBy: 'Jamie Sunshine',
    expiry: 90,
  },
  {
    productInformation: "Canyon Ridge® Collection Ultra-Grain® Series with Intellicore®",
    cartName: "Michigan_Classic14209123",
    shippingPoint: "ABC Plant",
    createdBy: 'Steve Benneth...',
    expiry: 4,
  },
];

export default data;
